server:
  port: 0
  error:
    include-message: always
spring:
  application:
    name: msapp-users
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
logging:
  file:
    name: ./logs/mytest.log
  level:
    org.springframework.security: TRACE
    #root: "INFO"
    #org.springframework: "INFO"
    #com.test.myapp.controllers: "ERROR"
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  logback:
    rollingpolicy:
      max-history : 1 #num of days
      max-file-size : 10KB
      file-name-pattern : "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
management:
  endpoints:
    web:
      base-path: "/" #instead "actuator/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: "prometheus" #only prometheus endpoint is active
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
#tracing: #jaeger
#  url: http://localhost:4318/v1/traces
