server:
    port: 8080
spring:
  datasource:
      url: jdbc:postgresql://postgres:5432/users_service
      username: users_service
      password: dev
app:
  url:
    fraud: ${URL-FRAUDSERVICE}

'To setup ENV in Kubernetes:'
'env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: your-config-map
          key: dbHost
'