server:
    port: 8080
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/dev
      username: dev
      password: dev
app:
  serviceurl:
    users: "http://127.0.0.1:8080"
    antifraud: "http://127.0.0.1:8081"