server:
  port: 8080
spring:
  application:
      name: msapp-apigateway
  main:
    web-application-type: reactive
  cloud:
     gateway:
        routes:
          - id: users
            uri: http://127.0.0.1:8081
            predicates:
              - Path=/users/**
            filters:
              - UserAuthenticationFilter

          - id: fraudchecks
            uri: http://127.0.0.1:8082
            predicates:
              - Path=/antifraud/**
            filters:
              - UserAuthenticationFilter

          - id: notifications
            uri: http://127.0.0.1:8083
            predicates:
              - Path=/notifications/**
            filters:
              - UserAuthenticationFilter
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: dev
    password: dev
  flyway:
    enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
management: #Enables access to http://127.0.0.1:8080/actuator/gateway/routes
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
#  tracing:
#    sampling:
#      probability: 1.0
app:
  baseurl: "http://127.0.0.1:8080"