create user USERS_SERVICE with password 'dev';
create user ANTIFRAUD_SERVICE with password 'dev';
create user NOTIFICATION_SERVICE with password 'dev';
create database USERS_SERVICE;
create database ANTIFRAUD_SERVICE;
create database NOTIFICATION_SERVICE;
grant all privileges on database USERS_SERVICE to USERS_SERVICE;
grant all privileges on database ANTIFRAUD_SERVICE to ANTIFRAUD_SERVICE;
grant all privileges on database NOTIFICATION_SERVICE to NOTIFICATION_SERVICE;
grant all privileges on database USERS_SERVICE to dev;
grant all privileges on database ANTIFRAUD_SERVICE to dev;
grant all privileges on database NOTIFICATION_SERVICE to dev;