CREATE SCHEMA IF NOT EXISTS NOTIFICATION_SERVICE;

GRANT ALL PRIVILEGES ON SCHEMA NOTIFICATION_SERVICE TO DEV;
GRANT ALL PRIVILEGES ON SCHEMA NOTIFICATION_SERVICE TO NOTIFICATION_SERVICE;

CREATE TABLE NOTIFICATION_SERVICE.notifications
(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    TIME_SENT TIMESTAMP,
    MESSAGE_BODY VARCHAR(100)
)


