CREATE SCHEMA IF NOT EXISTS FRAUD_SERVICE;

GRANT ALL PRIVILEGES ON DATABASE FRAUD_SERVICE TO DEV;
GRANT ALL PRIVILEGES ON DATABASE FRAUD_SERVICE TO FRAUD_SERVICE;

CREATE TABLE IF NOT EXISTS FRAUD_SERVICE.FRAUDCHECKS
(
    ID SERIAL PRIMARY KEY,
    USER_ID      INTEGER,
    DATE_CHECKED TIMESTAMP,
    IS_FRAUDSTER BOOLEAN
);


