CREATE SCHEMA IF NOT EXISTS ANTIFRAUD_SERVICE;
CREATE TABLE IF NOT EXISTS ANTIFRAUD_SERVICE.FRAUDCHECKS
(
    ID SERIAL PRIMARY KEY,
    USER_ID      INTEGER,
    DATE_CHECKED TIMESTAMP,
    IS_FRAUDSTER BOOLEAN
);


