INSERT INTO ANTIFRAUD_SERVICE.fraudchecks (USER_ID, DATE_CHECKED, IS_FRAUDSTER) VALUES(1, CURRENT_TIMESTAMP, false);
INSERT INTO ANTIFRAUD_SERVICE.fraudchecks (USER_ID, DATE_CHECKED, IS_FRAUDSTER) VALUES(2, CURRENT_TIMESTAMP, false);
INSERT INTO ANTIFRAUD_SERVICE.fraudchecks (USER_ID, DATE_CHECKED, IS_FRAUDSTER) VALUES(3, CURRENT_TIMESTAMP, false);
INSERT INTO ANTIFRAUD_SERVICE.fraudchecks (USER_ID, DATE_CHECKED, IS_FRAUDSTER) VALUES(4, CURRENT_TIMESTAMP, false);
INSERT INTO ANTIFRAUD_SERVICE.fraudchecks (USER_ID, DATE_CHECKED, IS_FRAUDSTER) VALUES(5, CURRENT_TIMESTAMP, false);
INSERT INTO ANTIFRAUD_SERVICE.fraudchecks (USER_ID, DATE_CHECKED, IS_FRAUDSTER) VALUES(6, CURRENT_TIMESTAMP, false);
INSERT INTO ANTIFRAUD_SERVICE.fraudchecks (USER_ID, DATE_CHECKED, IS_FRAUDSTER) VALUES(7, CURRENT_TIMESTAMP, false);